os: Visual Studio 2015

platform:
  - x64
  - x86

environment:
  NODEJS_VERSION: "6"
  RUST_BACKTRACE: 1
  matrix:
    - NODE_ARCHITECTURE: x64
      RUST_TOOLCHAIN: stable-x86_64-pc-windows-msvc

    - NODE_ARCHITECTURE: x86
      RUST_TOOLCHAIN: stable-i686-pc-windows-msvc

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:NODE_ARCHITECTURE
  - npm config set msvs_version 2015
  - node -e "console.log(process.argv[0], process.arch, process.versions)"

  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-toolchain %RUST_TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup show
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd tests
  - npm test

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
