[package]
name = "neon"
version = "0.3.1"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "A safe abstraction layer for Node.js."
readme = "README.md"
documentation = "https://api.neon-bindings.com/neon/index.html"
homepage = "https://www.neon-bindings.com"
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
exclude = ["neon.jpg"]
build = "build.rs"

# Sharing the name of the library produced by neon-runtime allows the
# `build.rs` script for Neon projects to find the path to `node.lib`
# in Windows.
#
# See also: http://doc.crates.io/build-script.html#the-links-manifest-key
links = "neon-runtime"

[build-dependencies]
neon-build = { version = "=0.3.1", path = "crates/neon-build" }

[dev-dependencies]
rustc_version = "0.2"
lazy_static = "1.4.0"

[dependencies]
cslice = "0.2"
semver = "0.9.0"
neon-runtime = { version = "=0.3.1", path = "crates/neon-runtime" }

[workspace]
members = ["crates/neon-build", "crates/neon-runtime"]
exclude = ["test"]
