[package]
name = "neon"
version = "0.1.11"
authors = ["Dave Herman <dherman@mozilla.com>"]
description = "A safe abstraction layer for Node.js."
documentation = "https://docs.neon-bindings.com/neon/index.html"
homepage = "https://www.neon-bindings.com"
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
exclude = ["neon.jpg"]

[dependencies]
cslice = { version = "=0.1.1", path = "crates/cslice" }
neon-sys = { version = "=0.1.11", path = "crates/neon-sys" }
