[package]
name = "neon"
version = "0.1.12"
authors = ["Dave Herman <dherman@mozilla.com>"]
description = "A safe abstraction layer for Node.js."
documentation = "https://docs.neon-bindings.com/neon/index.html"
homepage = "https://www.neon-bindings.com"
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
exclude = ["neon.jpg"]
build = "build.rs"

# Sharing the name of the library produced by neon-runtime allows the
# `build.rs` script for Neon projects to find the path to `node.lib`
# in Windows.
#
# See also: http://doc.crates.io/build-script.html#the-links-manifest-key
links = "neon-runtime"

[dependencies]
cslice = "0.2"
neon-runtime = { version = "=0.1.12", path = "crates/neon-runtime" }
