[package]
name = "neon-macros"
version = "0.9.0"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Procedural macros supporting Neon"
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[features]
napi = []

[dependencies]
quote = "1"
syn = { version = "1", features = ["full"] }
