[package]
name = "neon-macros"
version = "0.5.3"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Build logic required for Neon projects."
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[features]
napi = []

[dependencies]
quote = "1"
syn = { version = "1", features = ["full"] }

[dev-dependencies.neon]
version = "*"
path = "../.."
features = ["proc-macros"]
