[package]
name = "neon-build"
version = "0.3.1"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Build logic required for Neon projects."
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"

[dependencies]

[features]
default = []
n-api = []
