[package]
name = "neon-runtime"
version = "0.2.0"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Exposes Node and V8 C++ API's for use by Neon."
repository = "https://github.com/neon-bindings/neon"
license = "MIT/Apache-2.0"

# libneon.a gets linked in with this package
links = "neon"

# this script builds libneon.a
build = "build.rs"

[build-dependencies]
gcc = "0.3.52"
regex = "0.2"
