name: cargo-cp-artifact

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
      - next/*
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - next/*

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      includes: ${{ steps.define.includes }}
    steps:
      - name: Define Cross-Compilation Target Matrix
        id: define
        uses: dherman/target-matrix@v1
        with:
          toolchain: rust
          windows-latest: x86_64-pc-windows-msvc
          macos-latest: x86_64-apple-darwin
          ubuntu-latest: x86_64-unknown-linux-gnu x86_64-unknown-freebsd x86_64-unknown-openbsd

  build:
    needs: matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        includes: ${{ needs.matrix.includes }}
    steps:
      - name: Show Target
        run: echo "${{ matrix.target }}"
