name: Test on Windows

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    strategy:
    fail-fast: false
      matrix:
        node-version: [12, 14, 15]
        rust-toolchain: [stable, beta]
        rust-target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust ${{ matrix.rust-toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        target: ${{ matrix.rust-target }}
        default: true
        override: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use npm v6
      if: ${{ matrix.node-version == '15' }}
      run: npm install -g npm@6
    - name: Install libclang
      uses: KyleMayes/install-llvm-action@01144dc97b1e2693196c3056414a44f15180648b
      with:
        version: "10"
        directory: ${{ runner.temp }}/llvm
    # - name: update node-gyp to latest
    #   # https://github.com/nodejs/node-gyp/issues/1933#issuecomment-586915535
    #   run: npm install -g node-gyp@latest
    - run: npm config set msvs_version 2019
    - name: run cargo test
      run: cargo test --release --target=${{ matrix.rust-target }}
      env:
        LIBCLANG_PATH: ${{ runner.temp }}/llvm/bin
    - name: run CLI test
      working-directory: ./create-neon
      run: npm test
